workflows:
  version: '2'
    build_on_release_branches:
      jobs:
        - go_build_mac:
          # matrix could be used to trigger, say, many versions of this on various platforms, etc
            filters:
              branches:
                only: master

jobs:
  go_build_mac:
    macos:
      xcode: '13.1.0'
    steps:
      - run:
        name: checkout
        command: git clone --depth 1 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH"
      - run:
        name: run build script
        command: python3 build.py
