workflows:
  version: 2
  build_on_release_branches:
    jobs:
      - go_build_mac:
        # matrix could be used to trigger, say, many versions of this on various platforms, etc
          filters:
            branches:
              only: master
      - go_build_linux:
          filters:
            branches:
              only: circle_linux

jobs:
  go_build_mac:
    macos:
      xcode: '12.4.0'
    steps:
      - run:
          name: checkout
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git clone --depth 1 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH"
      - run:
          name: install deps
          command: |
            brew update
            brew install swig@4.0.2
      - run:
          name: run build script
          command: python3 build.py
          working_directory: PDFNetWrappers
  go_build_linux:
    docker:
      - image: cimg/go:1.15
    steps:
      - run:
          name: checkout
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git clone --depth 1 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH"
      - run:
          name: install deps
          command: |
            sudo apt update
            sudo apt install -y python3 cmake
      - run:
          name: run build script
          command: python3 build.py
          working_directory: PDFNetWrappers
