name: GoLinux with Custom PDFTron/Wrappers Branch
on:
  workflow_dispatch:
    inputs:
      pdftron_download_link:
        description: "A link to a PDFTron core tar/zip file. Defaults to current release."
        type: string
        default: 'http://www.pdftron.com/downloads/PDFNetC64.tar.gz'
      wrapper_branch:
        description: "The wrapper branch to execute on. Defaults to master."
        type: string
        default: 'master'

jobs:
  go_build_test:
      name: Go Linux Build and Test
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ inputs.wrapper_branch }}

        # no need to install deps, all there already
        #- name: Install deps
        - name: Build and Test
          run: |
            python3 build.py -dl="${{ inputs.pdftron_download_link }}"
            cd build/PDFTronGo/pdftron/Samples
            ./runall_go.sh

        - uses: actions/upload-artifact@v3
          with:
            name: PDFTronGo
            path: build/PDFTronGo/pdftron
